---
title: "Visualización de Datos - PEC 2 - Mapa de cuadrículas"
author: "Ángel Moreno Prieto"
date: "2024-11-10"
output:
  html_document:
    highlight: default
    theme: readable
---

<body style="background-color:#fff8e3;">
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
```

```{r message=FALSE, warning=FALSE}
# Instalación de diferentes paquetes que serán necesarios
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
if (!require("ggplot2")) install.packages("ggplot2")
library(ggplot2)
if (!require("geofacet")) install.packages("geofacet")
library(geofacet)
# Geofacet: https://cran.r-project.org/web/packages/geofacet/vignettes/geofacet.html
```

# Evolución del porcentaje de paro por provincia en el periodo 2021-2023 {-}

```{r message=FALSE, warning=FALSE}
df <- read.csv("./data/unemployment_spain.csv", fileEncoding="latin1", colClass = c("code" = "character"))
udf <- df %>%
  group_by(code) %>%
  arrange(Periodo) %>%
  mutate(
    Periodo = factor(Periodo, levels = unique(Periodo)),
    Tendencia = (last(Total) - first(Total)) / abs(first(Total))
  ) %>%
  ungroup()
```

```{r message=FALSE, warning=FALSE, fig.width=12, fig.height=8}
ggplot(udf, aes(Periodo, Total, group = 1)) +
  geom_line(aes(color = Tendencia), size = 1.2) +
  scale_color_gradient2(
    low = "darkgreen",
    mid = "yellow3",
    high = "red3",
    midpoint = 0,
    limits = c(-0.6, 0.6)
  ) +
  facet_geo(~ code, grid = spain_prov_grid1, label = "name", scales = "free_y") +
  scale_x_discrete(labels = c("'21", "", "", "", "'22", "", "", "", "'23", "", "", "", "'24", "", "", "")) +
  theme_bw()
```

***Fuentes:***

- *INE (https://www.ine.es/jaxiT3/Tabla.htm?t=3996)*
  


